kojira: don't fail on deleted items
py2 relict - dict.values() is now iterator, so
RuntimeError: dictionary changed size during iteration
can be raised when needed repo was deleted during the iteration.

Simple fix to use copy instead of iterator will fix this.