ignore inodes when running rpmdiff.
https://koji.fedoraproject.org/koji/taskinfo?taskID=21649395
failed in the rpmdiff stage with
BuildError: The following noarch package built differently on different architectures: python3-ipaserver-4.6.0-1.fc27.noarch.rpm
rpmdiff output was:
error: cannot open Packages index using db5 - Permission denied (13)
error: cannot open Packages database in /var/lib/rpm
error: cannot open Packages database in /var/lib/rpm
....N...... /usr/lib/python3.6/site-packages/ipaserver/install/__pycache__/ipa_pkinit_manage.cpython-36.opt-1.pyc
....N...... /usr/lib/python3.6/site-packages/ipaserver/install/__pycache__/ipa_pkinit_manage.cpython-36.pyc
on investigation the files on aarch64 and ppc64 were using 2 inodes
on x86_64, i686, armv7hl, ppc64le, and s390x using 1 inode.
if I manually run the diff with --ignore S changed to N the diff passes
given that we already ignore sizes we should ignore inodes used also

Signed-off-by: Dennis Gilmore <dennis@ausil.us>